firstname: "Max"
lastname: "Mustermann"
birth_dd: 1
birth_mm: 1
birth_yyyy: 1987
gmail_id: "maxmuster123" # for maxmuster123+001@gmail.com ...
gmail_start: 1
gmail_end: 100
pw: "password123"
street: "Straße 1"
zipcode: "56789"
city: "Berlin"
apply_wait: 5
2captcha_userkey: 65586210a12683de139c1b2hstz34904
colabox_image: image.jpg
